apiVersion: 1
datasources:
  - name: Influx
    uid:  grip_ds
    type: influxdb
    url:  http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: grip
      defaultBucket: grip
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
  - name: Tempo
    uid: tempo_ds
    type: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: false
    editable: false