version: "3.9"

services:
  grip-web:
    build: .
    container_name: grip_web
    restart: always
    devices:  # pass the USB serial adapter through
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on: [ otel, influxdb ]
    env_file:
      - .env
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=garage
      - INFLUX_BUCKET=grip
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=grip-web
    networks: [gripnet]
    ports:
      - "80:80"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    volumes:
      - ./data/influx:/var/lib/influxdb2
      - ./config/influx:/etc/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_PW}
      - DOCKER_INFLUXDB_INIT_ORG=grip
      - DOCKER_INFLUXDB_INIT_BUCKET=grip
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks: [gripnet]
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    restart: always
    user: "0"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks: [gripnet]
    ports:
      - "3000:3000"
    depends_on: [influxdb]

  telegraf:
    image: telegraf:1.32-alpine
    container_name: telegraf
    depends_on: [ influxdb ]
    env_file:
      - .env
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
    networks: [ gripnet ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    user: "0"
  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks: [ gripnet ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports: ["3200:3200", "4317:4317", "4318:4318"]            # OTLP, Jaeger & HTTP
    restart: always
    user: "0"

networks:
  gripnet:
    driver: bridge