version: "3.9"

services:
  grip-web:
    build: .
    container_name: grip_web
    restart: always
    devices:  # pass the USB serial adapter through
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on: [influxdb]
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=garage
      - INFLUX_BUCKET=grip
    networks: [gripnet]
    ports:
      - "80:80"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    volumes:
      - ./data/influx:/var/lib/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${ADMIN_PW}
      - INFLUXDB_BUCKET=grip
      - INFLUXDB_ORG=garage
      - INFLUXDB_RETENTION=730d
      - INFLUXDB_TOKEN=${INFLUX_TOKEN}
    networks: [gripnet]
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    user: "0"
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
    networks: [gripnet]
    ports:
      - "3000:3000"
    depends_on: [influxdb]

networks:
  gripnet:
    driver: bridge